config/routes.rb
SignMaker::Application.routes.draw do
  resources :employees

  resources :signatures

  resources :clients

  root :to => 'employees#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :cell_phone, :name, :nextel, :other_phone, :position, :radio, :userid, :hide_picture, :foroutlook
end

app/models/signature.rb
class Signature < ActiveRecord::Base
  attr_accessible :client_id, :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	

  	protect_from_forgery
    USERS = { "c0ldw311" => "tUl@tra35" }

      before_filter :authenticate
      private

      def authenticate
        authenticate_or_request_with_http_digest do |username|
          USERS[username]
        end
      end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
        include ERB::Util

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
      require 'nokogiri'
    @employee = Employee.new(params[:employee])
    doc = Nokogiri::HTML::Document.new
    doc.encoding = 'UTF-8'
    
    node = doc.fragment(params[:employee][:position])
    @employee.position = node.to_html(encoding:'US-ASCII')
    
    node = doc.fragment(params[:employee][:name])
    @employee.name = node.to_html(encoding: 'US-ASCII')

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

    # PUT /employees/1
    # PUT /employees/1.json
    def update
        require 'nokogiri'
        
        @employee = Employee.find(params[:id])
        doc = Nokogiri::HTML::Document.new
        doc.encoding = 'UTF-8'
        
        node = doc.fragment(params[:employee][:position])
        params[:employee][:position] = node.to_html(encoding:'US-ASCII')
        
        node = doc.fragment(params[:employee][:name])
        params[:employee][:name] = node.to_html(encoding: 'US-ASCII')


        respond_to do |format|
            if @employee.update_attributes(params[:employee])
                
                format.html { redirect_to @employee, notice: 'Se ha actualizado correctamente.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @employee.errors, status: :unprocessable_entity }
            end
        end
    end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  # GET /signatures
  # GET /signatures.json
  def index
    @signatures = Signature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signatures }
    end
  end

  # GET /signatures/1
  # GET /signatures/1.json
  def show
    @signature = Signature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signature }
    end
  end

  # GET /signatures/new
  # GET /signatures/new.json
  def new
    @signature = Signature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signature }
    end
  end

  # GET /signatures/1/edit
  def edit
    @signature = Signature.find(params[:id])
  end

  # POST /signatures
  # POST /signatures.json
  def create
    @signature = Signature.new(params[:signature])

    respond_to do |format|
      if @signature.save
        format.html { redirect_to @signature, notice: 'Signature was successfully created.' }
        format.json { render json: @signature, status: :created, location: @signature }
      else
        format.html { render action: "new" }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /signatures/1
  # PUT /signatures/1.json
  def update
    @signature = Signature.find(params[:id])

    respond_to do |format|
      if @signature.update_attributes(params[:signature])
        format.html { redirect_to @signature, notice: 'Signature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signatures/1
  # DELETE /signatures/1.json
  def destroy
    @signature = Signature.find(params[:id])
    @signature.destroy

    respond_to do |format|
      format.html { redirect_to signatures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.description %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Description:</b>
  <%= @client.description %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr/>
<p>
En esta pantalla pudes agregar los datos de los usuarios para la creación de su firma de correo electrónico.</p>
<p><strong>No es necesario que hagas ningún tipo de codificación al introducir datos. Cuando modifique datos hay que eliminar la codificación y teclear de nuevo el texto.</strong></p>
  <div class="field">
    <%= f.label :userid, "Nombre de usuario (UserId)" %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :hide_picture, "Ocultar Fotografia"%><br/>
    <%= f.select :hide_picture, [['No',0],['Si',1]] %>
    </div>
    
    <div class="field">
      <%= f.label :foroutlook, "Formato de Outlook"%><br/>
      <%= f.select :foroutlook, [['No',0],['Si',1]] %>
      </div>
  <div class="field">
    <%= f.label :name, "Nombre:" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position, "Puesto:" %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field", "Otro Teléfono:">
    <%= f.label :other_phone %><br />
    <%= f.text_field :other_phone %>
  </div>
  <div class="field">
    <%= f.label :cell_phone, "Célular" %><br />
    <%= f.text_field :cell_phone %>
  </div>
  <div class="field", "Nextel:">
    <%= f.label :nextel %><br />
    <%= f.text_field :nextel %>
  </div>
  <div class="field", "Nextel ID:">
    <%= f.label :radio %><br />
    <%= f.text_field :radio %>
  </div>
  <div class="actions">
    <%= f.submit "Aceptar" %>
  </div>
<% end %>

app/views/employees/_privacy.html.erb
<p align="justify" style="font-family:Arial, Helvetica, sans-serif; font-size:10px; color:#999999"><strong>Aviso de Privacidad de Correo Electrónico:</strong><br/>
La informaci&oacute;n contenida en este correo electr&oacute;nico y anexos es confidencial y propiedad de Coldwell Banker Acueducto. Está dirigida &uacute;nicamente para el uso del individuo o entidad a la que fue dirigida y puede contener informaci&oacute;n propietaria que no es del dominio p&uacute;blico. Si has recibido este correo por error o no eres el destinatario al que fue enviado, por favor notifica al remitente de inmediato y borra este mensaje de tu computadora. Cualquier uso, distribuci&oacute;n de este correo que no sea por el destinatario de intenci&oacute;n, queda prohibido.</p>
<p align="justify" style="font-family:Arial, Helvetica, sans-serif; font-size:10px; color:#999999"><strong>Privacy Notice e-mail:</strong><br/>
The information contained in this email and annexes is proprietary and confidential to Coldwell Banker Acueducto. It is intended solely for the use of the individual or entity to which it was addressed and may contain proprietary information that is not in the public domain. If you have received this email by mistake or you're not the recipient to which it was sent, please notify the sender immediately and delete this message from your computer
</p>

app/views/employees/edit.html.erb
<h1>Editar recurso</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @employee %> |
<%= link_to 'Atras', employees_path %>

app/views/employees/index.html.erb
<h1>Recursos<hr/></h1>
<p>Esta lista contiene los Recursos Humanos con los que cuenta la empresa</p>
<div>
<table border="1" width="100%   ">
  <tr>
    <th>Usuario</th>
    <th>Nombre</th>
    <th>Puesto</th>
    <th colspan="2">Acciones</th>

  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td align="center"><img src="http://www.cbacueducto.com.mx/images/signatures/<%= employee.userid %>.png"/></td>
    <td><%= link_to raw(employee.name), employee %></td>
    <td><%= raw(employee.position) %></td>
    <td align="center"><%= link_to 'Editar', edit_employee_path(employee) %></td>
    <td align="center"><%= link_to 'Eliminar', employee, method: :delete, data: { confirm: 'Estas seguro de que deseas borrar este recurso?' } %></td>
  </tr>
<% end %>
</table>
<div>
<br />

<%= link_to 'Nuevo recurso...', new_employee_path %>

app/views/employees/new.html.erb
<h1>Nuevo recurso</h1>

<%= render 'form' %>

<%= link_to 'Atras', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<% require 'rubygems' %>
<% require 'sanitize' %>
<!-- INICIO DE LA FIRMA DE CORREO ELECTRONICO --------------------------------------------------- -->
<%
    str = "BEGIN:VCARD" + "\n"
    str = str + "VERSION:3.0" + "\n"
    str = str + "N:" + Sanitize.clean(@employee.name).mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').to_s + "\n"
    str = str + "TITLE:" + Sanitize.clean(@employee.position).mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').to_s + "\n"
    str = str + "ORG:Coldwell Banker Acueducto" + "\n"
    str = str + "TEL;TYPE=WORK,VOICE:(33) 3611-3397" + "\n"
    str = str + "TEL;TYPE=CELL,VOICE:" + @employee.cell_phone + "\n"
    str = str + "EMAIL;TYPE=PREF,INTERNET:" + @employee.userid + "@cbacueducto.com.mx" + "\n"
    str = str + "END:VCARD"

%>
<!-- \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/ -->
<% if @employee.foroutlook != 1 %>
<p style="font-family:Arial, Helvetica, sans-serif">Saludos afectuosos / Kindest regards</p>
<p style="min-width: 800px">
<table width="100%" bgcolor="#ffffff" cellpadding="0" cellspacing="0" style="border: 1px solid #999999; background-image: url('http://www.cbacueducto.com.mx/images/signatures/signature_background.png');background-repeat: repeat-x; ">
  <tr>
  <td rowspan="5" width="5px">&nbsp;</td>
    <td width="200px" rowspan="5" ><img width="200px" height="100px" src="http://www.cbacueducto.com.mx/images/mail_signature_logo.png" alt="Coldwell Banker Acueducto" moz-do-not-send="true"/></td>
    <td rowspan="5" width="5px">&nbsp;</td>

    <td style="border-bottom: 1px solid #00488f"><br/><span style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #00488f"><%= raw @employee.name%> </span></td>
    <td rowspan="5" width="100px">
        <% if @employee.hide_picture != 1 %><div style="position: relative"><div id="picture" style="border: 3px solid #ffffff; background-image: url('http://www.cbacueducto.com.mx/images/signatures/<%= @employee.userid %>.png'); height: 136px; width: 118px; position: absolute; top: -60px; left: -20px; box-shadow: 3px 3px 4px #999999; -moz-box-shadow: 3px 3px 4px #999999; -webkit-box-shadow: 3px 3px 4px #999999;transform: rotate(5deg);
    -ms-transform: rotate(5deg); /* IE 9 */
    -webkit-transform: rotate(5deg); /* Safari and Chrome */
    -o-transform: rotate(5deg); /* Opera */
    -moz-transform: rotate(5deg); /* Firefox */"></div></div><% end %></td>
     <td rowspan="5" width="5px">&nbsp;</td>
    <td rowspan="5" width="100px"><img alt="Utilice la camara de su tel&eacute;fono inteligente para leer la informaci&oacute;n de contacto en este c&oacute;digo." src="http://chart.apis.google.com/chart?cht=qr&chs=400x400&chl=<%= str.to_uri%>" width="100%" height="100" moz-do-not-send="true"/></td>
     <td rowspan="5" width="5px">&nbsp;</td>
  </tr>
  <tr>
    <td><span style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size:12px; color: #00488f"><strong><%= raw @employee.position %></strong></span><span style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size:10px; color: #00488f">    
  
      <% if @employee.other_phone.length > 0 then %>
          &bull; Tel&eacute;fono: <%= @employee.other_phone %>
      <% end %>
      <% if @employee.cell_phone.length > 0 then %>
          &bull; Tel. Celul&aacute;r: <%= @employee.cell_phone %> 
      <% end %>
      <% if @employee.nextel.length > 0 then %>
          &bull; Nextel: <%= @employee.nextel %> 
      <% end %>      
      <% if @employee.radio.length > 0 then %>
          &bull; Nextel ID: <%= @employee.radio %> 
      <% end %>
          &bull; eMail: <a style="text-decoration:none; color: #000000;" href="mailto:<%= @employee.userid %>@cbacueducto.com.mx"><%= @employee.userid %>@cbacueducto.com.mx</a></span></td>
  </tr>
  <tr>
    <td><span style="font-family: Champagne, Arial, Helvetica, sans-serif; font-size: 18px; color:#00488f">Coldwell Banker Acueducto&reg;</span>&nbsp;<span style="font-family: Champagne, Arial, Helvetica, sans-serif; font-size:12px; color:#00488f">Lo que los Bienes Ra&iacute;ces deben ser</span>
    </td>
  </tr>
  <tr>
    <td><span style="font-family: Arial, Helvetica, sans-serif; font-size:10px; color:#00488f"><strong><a href="http://www.cbacueducto.com.mx" style="text-decoration:none; color: #000000;">http://www.cbacueducto.com.mx</a></strong> &bull; Tel&eacute;fono: +52 (33) 3611-3397</span></td>
  </tr>
    <tr><td><span style="font-family: Arial, Helvetica, sans-serif; font-size:10px; color:#00488f">Avenida Real Acueducto 360-A, 3er. Piso &bull; Colonia Puerta de Hierro &bull; Zapopan &bull; Jalisco, 45116</span></td></tr>
  <tr style="background-image: url('http://www.cbacueducto.com.mx/images/medium_blue_linen.jpg');"><td colspan="8">&nbsp;</td></tr>
</table>
</p>
<p>
<table><tr><td><img align="right" src="http://www.cbacueducto.com.mx/images/ecoicon.png" moz-do-not-send="true"/></td><td><p align="left" valign="middle" style="font-family:Arial, Helvetica, sans-serif; font-size:10px; color:#006600">No imprimir si no es necesario.<br/>Hay que proteger el Medio Ambiente.</p></td></tr></table>
</p>


<%= render 'privacy'%>

<% else %>


    <p style="font-family:Arial, Helvetica, sans-serif">Saludos afectuosos / Kindest regards</p>
    <p style="min-width: 800px">
    <table width="100%" bgcolor="#ffffff" cellpadding="0" cellspacing="0" style="border: 1px solid #999999;">
      <tr>
      <td rowspan="5" width="5px">&nbsp;</td>
        <td width="200px" rowspan="5"><img width="200px" height="100px" src="http://www.cbacueducto.com.mx/images/mail_signature_logo.png" alt="Coldwell Banker Acueducto" moz-do-not-send="true"/></td>
        <td rowspan="5" width="5px">&nbsp;</td>

        <td style="border-bottom: 1px solid #00488f"  width="100%"><br/><span style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #00488f"><%= raw @employee.name %></span></td>
        <td rowspan="5" width="100px"><% if @employee.hide_picture != 1 %>
            <img src="http://www.cbacueducto.com.mx/images/signatures/<%= @employee.userid %>.png" height="136" width="118"/><% end %></td>
         <td rowspan="5" width="5px">&nbsp;</td>
        <td rowspan="5" width="100px"><img alt="Utilice la camara de su tel&eacute;fono inteligente para leer la informaci&oacute;n de contacto en este c&oacute;digo." src="http://chart.apis.google.com/chart?cht=qr&chs=400x400&chl=<%= str.to_uri%>" width="150" height="150" moz-do-not-send="true"/></td>
         <td rowspan="5" width="5px">&nbsp;</td>
      </tr>
      <tr>
        <td><span style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size:12px; color: #00488f"><strong><%= raw @employee.position %></strong></span><span style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size:10px; color: #00488f">    

              <% if @employee.other_phone.length > 0 then %>
                  &bull; Tel&eacute;fono: <%= @employee.other_phone %>
              <% end %>
              <% if @employee.cell_phone.length > 0 then %>
                  &bull; Tel. Celul&aacute;r: <%= @employee.cell_phone %> 
              <% end %>
              <% if @employee.nextel.length > 0 then %>
                  &bull; Nextel: <%= @employee.nextel %> 
              <% end %>      
              <% if @employee.radio.length > 0 then %>
                  &bull; Nextel ID: <%= @employee.radio %> 
              <% end %>
              &bull; eMail: <a style="text-decoration:none; color: #000000;" href="mailto:rvega@cbacueducto.com.mx"><%= @employee.userid %>@cbacueducto.com.mx</a></span></td>
      </tr>
      <tr>
        <td><span style="font-family: Champagne, Arial, Helvetica, sans-serif; font-size: 18px; color:#00488f">Coldwell Banker Acueducto&reg;</span>&nbsp;<span style="font-family: Champagne, Arial, Helvetica, sans-serif; font-size:12px; color:#00488f">Lo que los Bienes Ra&iacute;ces deben ser</span>
        </td>
      </tr>
      <tr>
        <td><span style="font-family: Arial, Helvetica, sans-serif; font-size:10px; color:#00488f"><strong><a href="http://www.cbacueducto.com.mx" style="text-decoration:none; color: #000000;">http://www.cbacueducto.com.mx</a></strong> &bull; Tel&eacute;fono: +52 (33) 3611-3397</span></td>
      </tr>
        <tr><td><span style="font-family: Arial, Helvetica, sans-serif; font-size:10px; color:#00488f">Avenida Real Acueducto 360-A, 3er. Piso &bull; Colonia Puerta de Hierro &bull; Zapopan &bull; Jalisco, 45116</span></td></tr>
      <tr bgcolor="#416496"><td colspan="8">&nbsp;</td></tr>
    </table>
    </p>
    <p>
    <table><tr><td><img align="right" src="http://www.cbacueducto.com.mx/images/ecoicon.png" moz-do-not-send="true"/></td><td><p align="left" valign="middle" style="font-family:Arial, Helvetica, sans-serif; font-size:10px; color:#006600">No imprimir si no es necesario.<br/>Hay que proteger el Medio Ambiente.</p></td></tr></table>
    </p>

    <%= render 'privacy'%>

<% end %>

<!-- \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/ -->
<!-- FIN DE LA FIRMA DE CORREO ELECTRONICO -------------------------------------------- -->


<br/>
<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coldwell Banker&reg; Acueducto - Q&iuml;xi Generador de Firmas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content_wrapper">
<%= yield %>
</div>
</body>
</html>

app/views/signatures/_form.html.erb
<%= form_for(@signature) do |f| %>
  <% if @signature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signature.errors.count, "error") %> prohibited this signature from being saved:</h2>

      <ul>
      <% @signature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.number_field :client_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signatures/edit.html.erb
<h1>Editing signature</h1>

<%= render 'form' %>

<%= link_to 'Show', @signature %> |
<%= link_to 'Back', signatures_path %>

app/views/signatures/index.html.erb
<h1>Listing signatures</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Client</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signatures.each do |signature| %>
  <tr>
    <td><%= signature.name %></td>
    <td><%= signature.description %></td>
    <td><%= signature.client_id %></td>
    <td><%= link_to 'Show', signature %></td>
    <td><%= link_to 'Edit', edit_signature_path(signature) %></td>
    <td><%= link_to 'Destroy', signature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signature', new_signature_path %>

app/views/signatures/new.html.erb
<h1>New signature</h1>

<%= render 'form' %>

<%= link_to 'Back', signatures_path %>

app/views/signatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @signature.name %>
</p>

<p>
  <b>Description:</b>
  <%= @signature.description %>
</p>

<p>
  <b>Client:</b>
  <%= @signature.client_id %>
</p>


<%= link_to 'Edit', edit_signature_path(@signature) %> |
<%= link_to 'Back', signatures_path %>